// import bcrypt from "bcryptjs";
const data = {
  //   users: [
  //     {
  //       name: "John",
  //       email: "admin@example.com",
  //       password: bcrypt.hashSync("123456"),
  //       isAdmin: true,
  //     },
  //     {
  //       name: "Jane",
  //       email: "user@example.com",
  //       password: bcrypt.hashSync("123456"),
  //       isAdmin: false,
  //     },
  //   ],
  products: [
    {
      name: "midical1",
      slug: "midical-1",
      category: "heart ",
      image: "/images/prod1.jpg",
      isFeatured: true,
      featuredImage: "/images/prod1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "molestiae quas vel ",
    },
    {
      name: "midical2",
      slug: "midical-2",
      category: "Shirts",
      image: "/images/prod2.jpg",
      isFeatured: true,
      featuredImage: "/images/prod2.jpg",
      price: 80,
      brand: "Adidas",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/prod3.jpg",
      price: 90,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/prod4.jpg",
      price: 90,
      brand: "Oliver",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Smart looking pants",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "/images/prod5.jpg",
      price: 95,
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Pants",
      image: "/images/prod3.jpg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
  ],
  newProducts: [
    {
      name: "Acne (TF)",
      slug: "Acne-(TF)",
      description:
        "Tretinoin 0.025% Foam Tretinoin foam can be customized (0.05%, 0.1%) with same price",
      category: "Acne",
      image: "/images/prod1.jpg",
      brand: "brand 1",
      size: [
        {
          unit: "ml",
          price: "10",
          count: "30",
          numberonStock: 5,
        },
        {
          unit: "ml",
          price: "20",
          count: "50",
          numberonStock: 5,
        },
      ],
      requiredPrescription: false,
    },
    {
      name: "Acne",
      slug: "Acne",
      description: "Clindamycin 1% Tretinoin 0.025% Cream",
      category: "Acne",
      image: "/images/prod2.jpg",
      brand: "brand 2",
      size: [
        {
          unit: "gm",
          price: "10",
          count: "30",
          numberonStock: 5,
        },
        {
          unit: "ml",
          price: "20",
          count: "65",
          numberonStock: 5,
        },
      ],
      requiredPrescription: false,
    },
    {
      name: "Acne (N) ",
      slug: "Acne-(N) ",
      description: "Niacinamide 12% Azelaic acid 5% Zinc oxide 3% Cream",
      category: "Acne",
      image: "/images/prod3.jpg",
      brand: "brand 1",
      size: [
        {
          unit: "gm",
          price: "10",
          count: "30",
          numberonStock: 5,
        },
        {
          unit: "gm",
          price: "50",
          count: "60",
          numberonStock: 5,
        },
      ],
    },
    {
      name: "Acne (NC) ",
      slug: "Acne-(NC) ",
      description:
        "Tretinoin 0.025% Foam Tretinoin foam can be customized (0.05%, 0.1%) with same price",
      category: "Acne",
      image: "/images/prod1.jpg",
      brand: "brand 1",
      size: [
        {
          unit: "ml",
          price: "10",
          count: "30",
          numberonStock: 5,
        },
        {
          unit: "ml",
          price: "20",
          count: "50",
          numberonStock: 5,
        },
      ],
    },
  ],
};
export default data;
